In [1]:
'''1.what is python library? why do we use python library

A Python library is a collection of modules or packages containing pre-written code that can be used to 
perform specific tasks or functions without the need to write the code from scratch. Libraries in Python are 
designed to simplify and accelerate the development process by providing reusable components that can be 
easily integrated into your programs.'''

'1.what is python library? why do we use python library\n\nA Python library is a collection of modules or packages containing pre-written code that can be used to \nperform specific tasks or functions without the need to write the code from scratch. Libraries in Python are \ndesigned to simplify and accelerate the development process by providing reusable components that can be \neasily integrated into your programs.'

In [2]:
'''2.what is difference between numpy array and list
The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of 
the objects. For example, a NumPy array of strings can only contain strings and no other data types, but a
Python list can contain a mixture of strings, numbers, booleans and other objects.'''

'2.what is difference between numpy array and list\nThe main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of \nthe objects. For example, a NumPy array of strings can only contain strings and no other data types, but a\nPython list can contain a mixture of strings, numbers, booleans and other objects.'

In [3]:
#3.find the shape,size and dimension of the following array'''


In [48]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [49]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
arr.size

12

In [4]:
arr.shape

(3, 4)

In [5]:
arr.ndim

2

In [6]:
#4.write the python code to access the first row of the following array?'''
arr[0:1]

array([[1, 2, 3, 4]])

In [7]:
#5.how do you acess the element at the third row and fourth column form the given array 
arr[2,3]

12

In [ ]:
#6. write the code to extract all odd indexed elements form given numpy array
import numpy as np
def odd_indexed(arr):
    if arr[i]==arr[j]:
        print(i)
odd_indexed(arr)

In [9]:
#7.how can you generate a random 3x3 matrix with values between 0 and 1
np.random.randint(0,1,size=(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
#8. describe the difference np.random.rand and np.random.randn
'''
1.np.random.rand:

It generates random numbers from a uniform distribution over the interval [0, 1).
The output is in the range [0, 1), and all values have an equal probability of being generated.

2. np.random.randn:                           
It generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).'''

'np.random.rand:\n\nIt generates random numbers from a uniform distribution over the interval [0, 1).\nThe output is in the range [0, 1), and all values have an equal probability of being generated.\n np.random.randn:                           \nIt generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).'

In [11]:
#9.write the code to increase the dimensions of following array
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr1=np.expand_dims(arr,axis=0)
arr1


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [16]:
arr1.ndim

3

In [18]:
arr.ndim

2

In [20]:
#10.how to transpose the following array in numpy
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [29]:
#11.consider the following case
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
#index wise multiplication
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [31]:
# matrix multiplication
a@b

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [32]:
#add both matrices
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [34]:
#subract b form a
a-b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
#divide matrix B  by matrix A
b/a


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
#12.which function in NumPy  can be used to swap the byte order of an array
import numpy as np
arr.byteswap()


array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

In [50]:
#13.what is the significance of the np.linalg. inv function
'''The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix'''
arr1=np.array([[2,4],[4,4]])
inverse_arr=np.linalg.inv(arr1)
print('inveserse array',inverse_arr)
print('original array',arr1)

inveserse array [[-0.5   0.5 ]
 [ 0.5  -0.25]]
original array [[2 4]
 [4 4]]


In [53]:
#14.what does np.reshape function do, and how it is used
#The np.reshape function in NumPy is used to change the shape of an array without changing its data.
arr.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [55]:
#15.what is broadcasting in Numpy
'''
Broadcasting in NumPy is a powerful feature that allows arrays of different shapes and sizes to be 
combined in arithmetic operations. Broadcasting automatically expands the smaller array to match the
shape of the larger array, so that element-wise operations can be performed without the need for
explicit reshaping or copying of data.

The basic rule of broadcasting is that the dimensions of the arrays should be compatible. 
Two dimensions are considered compatible when:

They are equal.
One of them is 1.'''
import numpy as np

# Create a 2x3 array
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a 1x3 array
B = np.array([10, 20, 30])

# Broadcasting: B is automatically expanded to match the shape of A
result = A + B

print("Array A:")
print(A)

print("\nArray B:")
print(B)

print("\nResult after broadcasting:")
print(result)


Array A:
[[1 2 3]
 [4 5 6]]

Array B:
[10 20 30]

Result after broadcasting:
[[11 22 33]
 [14 25 36]]
